<#
    EagleCraft — install as Windows services (survives reboots)

    Installs two services:
      eaglecraft   the web panel, which supervises Paper 1.20.4 + the
                   BungeeCord/EaglerXServer proxy
      cloudflared  the tunnel that publishes them

    MUST be run from an ELEVATED PowerShell. Installing a service talks to the
    Service Control Manager, which denies non-administrators — that is the
    "Cannot establish a connection to the service control manager: Access is
    denied" error, and it is the only reason it fails.

        Right-click PowerShell -> Run as Administrator, then:
        cd "C:\ai shit\eaglecraft-src"
        .\service\install-services.ps1

    Uninstall:
        .\service\install-services.ps1 -Uninstall
#>

[CmdletBinding()]
param(
    [switch]$Uninstall,
    [int]$Port = 8081,
    [int]$SmpPort = 25577,
    [int]$RamMb = 8192,
    [int]$ProxyRamMb = 512
)

$ErrorActionPreference = 'Stop'

function Say  ($m) { Write-Host "==> $m" -ForegroundColor Green }
function Warn ($m) { Write-Host "  !! $m" -ForegroundColor Yellow }
function Die  ($m) { Write-Host "  !! $m" -ForegroundColor Red; exit 1 }

# --- elevation ------------------------------------------------------------
$identity  = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host ""
    Die @"
This script must run as Administrator.

  Close this window, right-click PowerShell -> 'Run as Administrator',
  then re-run:

      cd "$(Split-Path -Parent $PSScriptRoot)"
      .\service\install-services.ps1
"@
}

$Repo    = Split-Path -Parent $PSScriptRoot
$Runtime = Join-Path $Repo 'runtime'
$WinSW   = Join-Path $Runtime 'eaglecraft-service.exe'
$SvcXml  = Join-Path $Runtime 'eaglecraft-service.xml'
$CfExe   = Join-Path $Runtime 'cloudflared.exe'

Say "Repository: $Repo"

# --- uninstall path -------------------------------------------------------
if ($Uninstall) {
    Say 'Removing services'
    if (Test-Path $WinSW) {
        & $WinSW stop   2>$null | Out-Null
        & $WinSW uninstall 2>$null | Out-Null
        Write-Host '  eaglecraft removed'
    }
    if (Test-Path $CfExe) {
        & $CfExe service uninstall 2>$null | Out-Null
        Write-Host '  cloudflared removed'
    }
    Say 'Done.'
    exit 0
}

# --- locate a REAL python -------------------------------------------------
# Not "python3": in Git Bash that resolves to a Microsoft Store app-execution
# alias under %LOCALAPPDATA%\Microsoft\WindowsApps, which is a per-user
# reparse point that a LocalSystem service cannot follow.
Say 'Locating a real Python interpreter'
$Python = $null
$candidates = @()
try {
    $candidates += (& py -0p 2>$null |
        ForEach-Object { ($_ -replace '^\s*-V:\S+\s*\*?\s*', '').Trim() })
} catch { }
$candidates += @(
    'C:\Python314\python.exe', 'C:\Python312\python.exe', 'C:\Python311\python.exe',
    "$env:LOCALAPPDATA\Programs\Python\Python312\python.exe",
    "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe"
)
foreach ($c in $candidates) {
    if ([string]::IsNullOrWhiteSpace($c)) { continue }
    if ($c -like '*WindowsApps*') { continue }   # Store alias: unusable as a service
    if (Test-Path $c) { $Python = $c; break }
}
if (-not $Python) {
    Die 'No usable python.exe found. Install Python from python.org (not the Microsoft Store).'
}
$pyver = (& $Python --version 2>&1)
Write-Host "  $Python  ($pyver)"

# --- WinSW ----------------------------------------------------------------
if (-not (Test-Path $WinSW)) {
    Say 'Downloading WinSW service wrapper'
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -UseBasicParsing `
        -Uri 'https://github.com/winsw/winsw/releases/download/v2.12.0/WinSW-x64.exe' `
        -OutFile $WinSW
}
Write-Host "  wrapper: $WinSW"

# --- stop anything already running from a shell ---------------------------
Say 'Stopping any panel started from a terminal'
Push-Location $Repo
try { & $Python 'server.py' '--shutdown' } catch { Warn "shutdown probe: $_" }
Pop-Location

# --- generate the service definition --------------------------------------
Say 'Writing service definition'
$xml = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by service\install-services.ps1. Edit that, not this. -->
<service>
  <id>eaglecraft</id>
  <name>EagleCraft SMP</name>
  <description>EagleCraft vanilla SMP: web panel supervising Paper 1.20.4 and the BungeeCord/EaglerXServer proxy.</description>

  <executable>$Python</executable>
  <arguments>server.py</arguments>
  <workingdirectory>$Repo</workingdirectory>

  <env name="PORT" value="$Port" />
  <env name="SMP_PORT" value="$SmpPort" />
  <env name="SMP_RAM_MB" value="$RamMb" />
  <env name="SMP_PROXY_RAM_MB" value="$ProxyRamMb" />
  <env name="AUTOSTART_SMP" value="1" />
  <env name="PYTHONUNBUFFERED" value="1" />

  <!-- Never hard-kill the panel: that kills Paper with no save, rolling the
       world back to the last autosave and risking region corruption.
       --shutdown stops the proxy, flushes the world, then stops Paper, and
       blocks until done (~65s measured). -->
  <stopexecutable>$Python</stopexecutable>
  <stoparguments>server.py --shutdown</stoparguments>
  <stoptimeout>150 sec</stoptimeout>
  <stopparentprocessfirst>false</stopparentprocessfirst>

  <startmode>Automatic</startmode>
  <delayedAutoStart>true</delayedAutoStart>
  <onfailure action="restart" delay="30 sec" />
  <resetfailure>1 hour</resetfailure>

  <logpath>$Repo\logs</logpath>
  <log mode="roll-by-size">
    <sizeThreshold>10240</sizeThreshold>
    <keepFiles>5</keepFiles>
  </log>
</service>
"@
Set-Content -Path $SvcXml -Value $xml -Encoding UTF8
Write-Host "  $SvcXml"

# --- install + start the panel service ------------------------------------
Say 'Installing service: eaglecraft'
if (Get-Service -Name 'eaglecraft' -ErrorAction SilentlyContinue) {
    Warn 'already installed - reinstalling to pick up config changes'
    & $WinSW stop 2>$null | Out-Null
    & $WinSW uninstall  | Out-Null
    Start-Sleep -Seconds 3
}
& $WinSW install
& $WinSW start
Start-Sleep -Seconds 5

# --- install + start cloudflared ------------------------------------------
if (Test-Path $CfExe) {
    $cfCfg = Join-Path $env:USERPROFILE '.cloudflared\config.yml'
    if (Test-Path $cfCfg) {
        Say 'Installing service: cloudflared'
        if (Get-Service -Name 'cloudflared' -ErrorAction SilentlyContinue) {
            Warn 'already installed - skipping'
        } else {
            & $CfExe --config $cfCfg service install
            Start-Sleep -Seconds 3
        }
    } else {
        Warn "no $cfCfg - run 'bash cloudflare.sh named <host> <host>' first"
    }
} else {
    Warn 'cloudflared.exe not in runtime/ - run cloudflare.sh first'
}

# --- report ---------------------------------------------------------------
Say 'Status'
Get-Service -Name 'eaglecraft', 'cloudflared' -ErrorAction SilentlyContinue |
    Format-Table Name, Status, StartType -AutoSize

Write-Host ''
Write-Host '  The SMP now starts automatically at boot.' -ForegroundColor Green
Write-Host "  Panel:    http://localhost:$Port"
Write-Host "  Logs:     $Repo\logs\eaglecraft.out.log"
Write-Host '  Control:  Start-Service eaglecraft / Stop-Service eaglecraft'
Write-Host '  Remove:   .\service\install-services.ps1 -Uninstall'
Write-Host ''
Write-Host '  Do NOT also run start.sh while the service is running -' -ForegroundColor Yellow
Write-Host '  both would fight over ports 8081 / 25565 / 25577.' -ForegroundColor Yellow
